source "http://rubygems.org"

gem "rake", "~> 0.9.2.2"
gem "net-ssh", "2.2.2"
gem "activerecord"
gem "activesupport"
gem "sinatra"
gem "sinatra-cache-assets"
gem "gcal4ruby"
gem "sqlite3"
gem "rack"
gem "rack-flash3"
gem "fastercsv"
gem "daemons"
gem "whenever"
gem "thor"
gem "foreman"
gem "colored"
gem "ghost"
gem "passenger"
gem "ruby-gmail"
gem "mime"

group :development, :test do
  gem "vmc"
  gem "debugger", :require => 'ruby-debug'
  # gem "ruby-debug-base19x", "~> 0.11.30.pre10"
  # gem "ruby-debug-ide"
  gem "factory_girl"
  gem "capistrano"
  gem "capistrano_colors"
  gem "capybara", "~> 1.1.1"
  gem "rspec", "~> 2.6.0"
  gem "launchy"
  gem "capybara-webkit"  # depends on: "apt-get install libqt4-dev"
  gem "shotgun"
  gem "thin"

  gem "vagrant", "1.0.3"
  gem "virtualbox"
  gem "vagrant-snap"

  gem "guard-coffeescript"
  gem "therubyracer"

  gem "drx"
  gem "hirb"
  gem "wirble"
  gem "interactive_editor"
  gem "awesome_print", :require => "ap"
end
